pgSQL rejected the update lines in populate-status-xxx change sets
Error executing SQL update FEEDENTRYSTATUSES s SET s.entryUpdated = (select e.updated from FEEDENTRIES e where e.id = s.entry_id):
ERROR: column "s" of relation "feedentrystatuses" does not exist